runtime: python39
instance_class: F1

env_variables:
  ALPACA_API_KEY: "AK7JFBTUXGCSLMT4HT1X"
  ALPACA_SECRET_KEY: "tZ8k80tGG26amIPFw6aLz7zaOKhTdz0D0AI8F93G"
  GMAIL_USER: "ryan.rigd@gmail.com"
  GMAIL_PASSWORD: "qfsabprwkhtwmzun"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: auto
  secure: always